name: Zola Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zola-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MTRNord/zola-check-manager@v1.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}