name: Zola Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zola-check:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/getzola/zola:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - uses: actions/checkout@v4
      - run: zola check