name: CSS Check

on:
  push:
    branches: [ main ]
    paths:
      - 'static/style.css'

jobs:
  css-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install lightningcss-cli
      - run: npm test